### ISSUE TITLE
DriveSoftwarePublisher | How to setup?

### ISSUE THREAD

**Issue by sarahhassan01** [adsau59/DriveSoftwarePublisher#1]
guys i try to execute this code but i get error, what is the preparation should i do first ??? 
i also follow steps in video but i write in cmd too but it doesn't work like his way! 
this is video link, and under video u will find all link resources
https://www.youtube.com/watch?v=TdtkTxmOgw8
link the project in github to download 
https://github.com/adsau59/DriveSoftwarePublisher

**Comment by adam-saudagar** [comment]
Hi, thanks for creating the issue

The code has changed since the prototype video, if u just want to use the program you can download the binaries of the prototype from here https://github.com/adsau59/DriveSoftwarePublisher/releases (0.0.1)

The reason it doesn't work is that the code was ported to .NET Core from standard .NET in the commit 82305aa0

**Comment by sarahhassan01** [comment]
i download last version but i still found erroe , because i don''t know
what i should else execcute the code


2018-07-30 17:47 GMT+02:00 adsau59 <notifications@github.com>:

**Comment by sarahhassan01** [comment]
can u tell me what is config which i should prepare ?!, and if i should
enable something or add any more file?

2018-07-30 18:02 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by adam-saudagar** [comment]
What error are you getting can you please copy it here?

For configuration, you just have to put SP.exe in environment path variable, then u can just use the program as shown in the video

**Comment by sarahhassan01** [comment]
where this file"SP.exe"!?

2018-07-30 18:06 GMT+02:00 adsau59 <notifications@github.com>:

**Comment by sarahhassan01** [comment]
and what is environment path??

2018-07-30 18:09 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by adam-saudagar** [comment]
Did u download the binaries from here? https://github.com/adsau59/DriveSoftwarePublisher/releases

And u can read how to use it on readme of that commit too
https://github.com/adsau59/DriveSoftwarePublisher/blob/72ead843b9aa15c92bc507c12b2918a713986507/README.MD

**Comment by sarahhassan01** [comment]
yes

**Comment by sarahhassan01** [comment]
so can u make video to how to download and execute (i know how to download
of course but to be sure from all steps, or if u have team viewer we can
walk step by step

2018-07-31 9:13 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

> yes
>

**Comment by sarahhassan01** [comment]
frist step i download file, so what is next step?

2018-07-31 9:16 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

> so can u make video to how to download and execute (i know how to download
> of course but to be sure from all steps, or if u have team viewer we can
> walk step by step
>
> 2018-07-31 9:13 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:
>
>> yes
>>
>

**Comment by sarahhassan01** [comment]
when i try to run

>

**Comment by sarahhassan01** [comment]
2018-07-31 9:30 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

> when i try to run
>
>>

**Comment by sarahhassan01** [comment]
2018-07-31 9:50 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

>
>
2018-07-31 9:30 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

> when i try to run
>
>>

**Comment by sarahhassan01** [comment]
do u here?

2018-07-31 10:27 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

>
>
> 2018-07-31 9:50 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:
>
>>
>>
> 2018-07-31 9:30 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:
>
>> when i try to run
>>
>>>

**Comment by adam-saudagar** [comment]
Sorry was busy,
1) download the file
2) extract it
3) copy the path where u extracted it
4) right click on my computer and go into properties
5) click on advance settings then click environmental variables
6) on the top scroll till u see "Path"
7) click edit and then click new, paste the path and press save
8) then run as u see it in the video

**Comment by sarahhassan01** [comment]
THANKS, should i download 3 file from link or just one?

2018-07-31 11:09 GMT+02:00 adsau59 <notifications@github.com>:

**Comment by sarahhassan01** [comment]
anyone of this three?


2018-07-31 11:22 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by sarahhassan01** [comment]
??


2018-07-31 11:25 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by sarahhassan01** [comment]
i follow your steps but i extract one file but i have a problem
can u install team viewer and work with me for 5 minutes only to fixed
this! :\

2018-07-31 11:31 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

> ??
>
>
2018-07-31 11:25 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by sarahhassan01** [comment]
2018-07-31 11:41 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by adam-saudagar** [comment]
I'm pretty busy now days, I'll let you know when i get free

**Comment by sarahhassan01** [comment]
ok, when u will get free

2018-07-31 11:55 GMT+02:00 adsau59 <notifications@github.com>:

**Comment by adam-saudagar** [comment]
Hi, please message me on discord when u want me to help u

My discord server :
https://discord.gg/V6e2fpc

**Comment by sarahhassan01** [comment]
where is  discord ?,
anyways i want help

2018-08-02 2:34 GMT+02:00 adsau59 <notifications@github.com>:

**Comment by adsau59** [comment]
Just press this link

**Comment by adam-saudagar** [comment]
Just press this link
https://discord.gg/V6e2fpc

**Comment by sarahhassan01** [comment]
i mentioned u


2018-08-05 0:29 GMT+02:00 adsau59 <notifications@github.com>:

**Comment by sarahhassan01** [comment]
i speek at this link as u asked "
https://discordapp.com/channels/430649963597266945/430649963597266947 "

2018-08-05 0:37 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by sarahhassan01** [comment]
hi, did u here?


2018-08-05 0:39 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by adam-saudagar** [comment]
thanks for creating the issue, please create another issue if u find any bugs, and reopen this one if u are not satisfied with the solution

**Comment by sarahhassan01** [comment]
hi dude
i want to open CMD from visual studio and projects online don't work, can u
help?

then i want exactly to connect CMD with another program to open cmd
directly after press on Button, how can i integrate both???

2018-08-05 11:47 GMT+02:00 adsau59 <notifications@github.com>:

**Comment by sarahhassan01** [comment]
hi. did u here?

2018-08-14 9:34 GMT+02:00 sara hassan <sarahassan01010@gmail.com>:

**Comment by adam-saudagar** [comment]
I don't understand what you mean

**Comment by sarahhassan01** [comment]
did u know revit? it a autodesk program using by architect , i develop in
revit and i make button and tab, but i need to make this button active and
give it action
this link took about Revit Button
https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2017/ENU/Revit-API/files/GUID-1547E521-59BD-4819-A989-F5A238B9F2B3-htm.html

i'm allready make this button but i need to let it have action when i press
on it by mouse , i need to open CMD when i press on it,
